services:
  - type: web
    name: xsave-server
    runtime: node
    buildCommand: npm install && pip install yt-dlp
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
